version: "3"

services:
  db:
    image: mariadb
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: test
  redis:
    image: redis
    restart: on-failure
    ports:
      - "6379:6379"
  openapi:
    image: swaggerapi/swagger-ui
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}:/data
    environment:
      SWAGGER_JSON: /data/openapi.yaml