version: "3"

services:
  db:
    image: mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: test
  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
  # openapi:
  #   image: swaggerapi/swagger-ui
  #   restart: unless-stopped
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ${PWD}:/data
  #   environment:
  #     SWAGGER_JSON: /data/openapi.yaml