// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: sms/v1/simple_message.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SmsClient is the client API for Sms service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SmsClient interface {
	TextMessageSend(ctx context.Context, in *TextMessageRequest, opts ...grpc.CallOption) (*SendMessageReply, error)
	TemplateMessageSend(ctx context.Context, in *TemplateMessageRequest, opts ...grpc.CallOption) (*SendMessageReply, error)
	AsyncResultQuery(ctx context.Context, in *AsyncResultQueryRequest, opts ...grpc.CallOption) (*AsyncResultQueryReply, error)
}

type smsClient struct {
	cc grpc.ClientConnInterface
}

func NewSmsClient(cc grpc.ClientConnInterface) SmsClient {
	return &smsClient{cc}
}

func (c *smsClient) TextMessageSend(ctx context.Context, in *TextMessageRequest, opts ...grpc.CallOption) (*SendMessageReply, error) {
	out := new(SendMessageReply)
	err := c.cc.Invoke(ctx, "/sms.v1.Sms/TextMessageSend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) TemplateMessageSend(ctx context.Context, in *TemplateMessageRequest, opts ...grpc.CallOption) (*SendMessageReply, error) {
	out := new(SendMessageReply)
	err := c.cc.Invoke(ctx, "/sms.v1.Sms/TemplateMessageSend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsClient) AsyncResultQuery(ctx context.Context, in *AsyncResultQueryRequest, opts ...grpc.CallOption) (*AsyncResultQueryReply, error) {
	out := new(AsyncResultQueryReply)
	err := c.cc.Invoke(ctx, "/sms.v1.Sms/AsyncResultQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmsServer is the server API for Sms service.
// All implementations must embed UnimplementedSmsServer
// for forward compatibility
type SmsServer interface {
	TextMessageSend(context.Context, *TextMessageRequest) (*SendMessageReply, error)
	TemplateMessageSend(context.Context, *TemplateMessageRequest) (*SendMessageReply, error)
	AsyncResultQuery(context.Context, *AsyncResultQueryRequest) (*AsyncResultQueryReply, error)
	mustEmbedUnimplementedSmsServer()
}

// UnimplementedSmsServer must be embedded to have forward compatible implementations.
type UnimplementedSmsServer struct {
}

func (UnimplementedSmsServer) TextMessageSend(context.Context, *TextMessageRequest) (*SendMessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TextMessageSend not implemented")
}
func (UnimplementedSmsServer) TemplateMessageSend(context.Context, *TemplateMessageRequest) (*SendMessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TemplateMessageSend not implemented")
}
func (UnimplementedSmsServer) AsyncResultQuery(context.Context, *AsyncResultQueryRequest) (*AsyncResultQueryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AsyncResultQuery not implemented")
}
func (UnimplementedSmsServer) mustEmbedUnimplementedSmsServer() {}

// UnsafeSmsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SmsServer will
// result in compilation errors.
type UnsafeSmsServer interface {
	mustEmbedUnimplementedSmsServer()
}

func RegisterSmsServer(s grpc.ServiceRegistrar, srv SmsServer) {
	s.RegisterService(&Sms_ServiceDesc, srv)
}

func _Sms_TextMessageSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).TextMessageSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sms.v1.Sms/TextMessageSend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).TextMessageSend(ctx, req.(*TextMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_TemplateMessageSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TemplateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).TemplateMessageSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sms.v1.Sms/TemplateMessageSend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).TemplateMessageSend(ctx, req.(*TemplateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sms_AsyncResultQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AsyncResultQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsServer).AsyncResultQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sms.v1.Sms/AsyncResultQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsServer).AsyncResultQuery(ctx, req.(*AsyncResultQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sms_ServiceDesc is the grpc.ServiceDesc for Sms service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sms_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sms.v1.Sms",
	HandlerType: (*SmsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TextMessageSend",
			Handler:    _Sms_TextMessageSend_Handler,
		},
		{
			MethodName: "TemplateMessageSend",
			Handler:    _Sms_TemplateMessageSend_Handler,
		},
		{
			MethodName: "AsyncResultQuery",
			Handler:    _Sms_AsyncResultQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sms/v1/simple_message.proto",
}
