# 是否开启调试模式
app_debug: true

consul:
  address: 127.0.0.1:8500
  path: kratos/sms.yaml
  scheme: http
  wait_time: 0.1s

server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s

data:
  database:
    driver: mongo
    # user and passwd set into env variable：KRATOS_MONGO_USER, KRATOS_MONGO_PASSWD
    source: mongodb://${MONGO_USER:admin}:${MONGO_PASSWD:admin}@mongodb_1:27017,mongodb_1:27018,mongodb_1:27019/?authSource=admin
    mongo:
      connect_timeout: 1s
      heartbeat_interval: 60s
      min_pool_size: 2
      max_pool_size: 10
      read_concern: majority
      read_prefer_mode: SECONDARY_PREFERRED
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

log:
  path: ${LOG_PATH:./logs/}
  default:
    level: 0 # 0 debug, 1 info, 2 warn, 3 error, 4 d_panic, 5 panic, 6 fatal
    filename: all.log
    time_format: MILLIS
    text_format: JSON
    max_size: 10
    max_backups: 100
    max_age: 7
    compress: true
  error:
    level: 2
    filename: error.log
    time_format: RFC3339_NANO
    text_format: CONSOLE
    max_size: 10
    max_backups: 100
    max_age: 7
    compress: false