# 是否开启调试模式
app_debug: true

consul:
  address: 127.0.0.1:8500
  path: kratos/sms.yaml
  scheme: http
  wait_time: 0.1s

server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s

data:
  database:
    driver: mongo
    # user and passwd set into env variable：KRATOS_MONGO_USER, KRATOS_MONGO_PASSWD
    source: mongodb://${MONGO_USER:admin}:${MONGO_PASSWD:admin}@mongodb_1:27017,mongodb_1:27018,mongodb_1:27019/?authSource=admin
    mongo:
      connect_timeout: 1s
      heartbeat_interval: 60s
      min_pool_size: 2
      max_pool_size: 10
      read_concern: majority
      read_prefer_mode: SECONDARY_PREFERRED
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

log:
  path: ${LOG_PATH:./logs/}
  default:
    level: DEBUG # CAN USE NUMBER: 0 DEBUG, 1 INFO, 2 WARN, 3 ERROR, 4 FATAL
    filename: all.log
    time_format: MILLIS
    text_format: JSON
    max_size: 10
    max_backups: 100
    max_age: 7
    compress: true
  error:
    level: 2  # CAN USE NUMBER: 0 DEBUG, 1 INFO, 2 WARN, 3 ERROR, 4 FATAL
    filename: error.log
    time_format: RFC3339_NANO
    text_format: CONSOLE
    max_size: 10
    max_backups: 100
    max_age: 7
    compress: false
  # 除 filter 外, log 的其他配置不支持动态调整, 调整值只能是日志级别对应的数字，否则无法生效
  filter: # 0 DEBUG, 1 INFO, 2 WARN, 3 ERROR, 4 FATAL
    biz_log_level: 0
    data_log_level: 0
    service_log_level: 0