version: '3.7'

services:

  mongodb_1:
    image: mongo:5
    hostname: mongodb_1
    command: --port 27017 --replSet rs1 --keyFile /etc/mongo-replication.key
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_1:/data/db
      - ./mongo-replication.key:/etc/mongo-replication.key

  mongodb_2:
    image: mongo:5
    hostname: mongodb_2
    command: --port 27018 --replSet rs1 --keyFile /etc/mongo-replication.key
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27018:27018
    volumes:
      - mongodb_data_2:/data/db
      - ./mongo-replication.key:/etc/mongo-replication.key
    depends_on:
      - mongodb_1

  mongodb_3:
    image: mongo:5
    hostname: mongodb_3
    command: --port 27019 --replSet rs1 --keyFile /etc/mongo-replication.key
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27019:27019
    volumes:
      - mongodb_data_3:/data/db
      - ./mongo-replication.key:/etc/mongo-replication.key
    depends_on:
      - mongodb_1

  redis:
    image: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
volumes:
  mongodb_data_1:
  mongodb_data_2:
  mongodb_data_3:
